### PR TITLE
 Sgratzl/thumbnails

### PR DESCRIPTION
**Pull request by sgratzl**
closes https://github.com/phovea/phovea_clue/issues/117

requires: 
 * patching your local config `<workspace>/config.json`: 
```
  "phovea_clue": {
    "server": "http://api/<nameoftheapp>"
  }
```
 * webpack-dev-content server doesn't work since this server can't be access from inside docker. So you `npm run watch:<nameoftheapp>` and access it via http://localhost:9000/<nameoftheapp>/
 * you might too restart the chrome container after the server is automatically restarted, since the connection might not be proper closed `docker-compose restart util_chrome`

### CODE REVIEW

**Comment by thinkh** [comment]
It doesn't work for me with the `provenance-retrieval` branch in Gapminder. 

I tried the following steps:

1. [Enabled thumbnails](https://github.com/Caleydo/gapminder/blob/master/src/index.ts#L29) in Gapminder
1. Merge this branch into `provenance-retrieval` branch
2. Patched the config.json with 
    ```
    "phovea_clue": {
      "server": "http://api/gapminder"
    }
    ```
2. `yo phovea:update` for the workspace
3. `npm install`
4. `docker-compose build api`
5. `docker-compose up`
6. `npm run watch:gapminder`
7. Open browser with http://localhost:9000/gapminder/

Requests for thumbnails are:
* This image
  grafik
* A thumbnail link to this non-existing image http://localhost:9000/gapminder/phovea_clue/assets/src/text.png for the _Start_ state (first state).

Any ideas what I'm missing?

**Comment by sgratzl** [comment]
do you have an persistent provenance graph? such that the server has the data.

**Comment by thinkh** [comment]
Ooops 😅 That might be the reason...

**Comment by thinkh** [comment]
With a persistent provenance graph it looks better in general. Now I'm getting some useful thumbnail URLs and sometimes also a thumbnails. 

However the log shows me some errors:
grafik

**Comment by sgratzl** [comment]
you burst the localStorage/sessionStorage with all the temporary provenance graphs ;)

we could think of applying a patch that remote provenance graphs should not be locally cloned but in a memory graph

**Comment by thinkh** [comment]
In general it looks really nice and works. Your suggestion might a good improvement. 👍 

Unfortunately, the screenshot is sometimes captured when the app hasn't finished the initialization.

Multiple thumbnails:
grafik

One bigger thumbnail:
grafik

**Comment by sgratzl** [comment]
I guess there is a timeout issue. I try 3 x 30seconds till the applications states it is ready (by adding a class to the body) if I run out I still take the screenshot. Could get better in the deployed version since caching applies there.

**Comment by thinkh** [comment]
Ok, since this works in general I'm going to merge this. Let's see how it behaves in the deployed version. We might need to tweak it later.

**Pull request merged**
